language: java

jdk:
- oraclejdk11

cache:
  directories:
  - $HOME/.m2

dist: trusty
# TODO: Change $DEPLOYMENT_BRANCH after tests
env:
  global:
    - DEPLOYMENT_BRANCH="setup-cd-flow"
    - APPLICATION_NAME="motosoup"
    - VERSION_MAJOR_NUMBER=0
    - VERSION_MINOR_NUMBER=1
    - VERSION_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - APPLICATION_VERSION="$VERSION_MAJOR_NUMBER.$VERSION_MINOR_NUMBER.$VERSION_BUILD_NUMBER"
    - WORKDIR="workdir"
    - PACKAGEDIR="$WORKDIR/package"


# addons:
#   sonarcloud:
#     organization: "baadamczyk-github"
#     token:
#       secure: "$SONAR_TOKEN"


jobs:
  include:
    # - stage: "Build And Verify"
    #   script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent
    #   # script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -DcheckCodeCoverage sonar:sonar
    # - stage: "Version Number Upgrade"
    #   script: bash .scripts/version-number-upgrade.sh
    #   if: branch = env(DEPLOYMENT_BRANCH)
    - stage: "Deploy New Release"
      script: 
        - bash .scripts/build-binaries.sh
        - bash .scripts/tag-release.sh
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        file_glob: true
        file: $PACKAGEDIR/*
        on:
          tags: true  
      if: branch = env(DEPLOYMENT_BRANCH)