language: java
jdk:
- oraclejdk11

cache:
  directories:
  - $HOME/.m2


env:
  global:
    - DEPLOYMENT_BRANCH="master"
    - APPLICATION_NAME="motosoup"
    - VERSION_MAJOR_NUMBER=0
    - VERSION_MINOR_NUMBER=1
    - VERSION_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - APPLICATION_VERSION="$VERSION_MAJOR_NUMBER.$VERSION_MINOR_NUMBER.$VERSION_BUILD_NUMBER"
    - WORKDIR="workdir"
    - PACKAGEDIR="$WORKDIR/package"

addons:
  sonarcloud:
    organization: "baadamczyk-github"
    token:
      secure: "dlqPtTveHPMf/78F6uQ3As0Tnv9u1u1r9zk4zrIt4HguMMBq09VJsgKGoozNs+bIK2bzvvedVGvlWPV874Nf1wWYLR5HJJ63onhnjGUreXvbaa1MFs/36/at6KT5tnCX25oD+Wv7kdJGdT4gt1Mh6lVtuHwGqaEMR6320/VDuvdb2nitm4Eg5cDKki2Xx+WuBgV+wFrw3gU9MVoKCtvRfuA/WQ9b72XL+OM39/1Bn9sAZ8zPJMq+1GfFD0HfepwKex8xBVNe1+sXQRz0A/bPrBrOpsA1WuaaEVU45BRq3hljmks68A5Ntli07ttRAr0poodzDZmfhUCPAK41ZOrwks79YxSa/zWqavGC41uMVlKspe8tnwIDqJTl37T76BIYj5uRAUB2O29Mooq3rm74ChPvkyjIGrJcpQPfUFu3PfRTnt6jM1fEY8iPKZafzRMESYfDtoZpeNqVAJPKtFfFhroGUc9suM+vGGSb2S7i8GLkuPSKZ0kU3lfC5SMbJXRqwbBVd7iXXPcpwSYBZHlgeKoq/NIwixTyv5ZxKYwihgl34q928c2ZfaudDThgFHirfHgswZ0pO/Pzw7QQ4UUOYNeNNGwFr9Ft9z/s7D7PDhyVgg6EE1eXkI1c4qydETm59kU/qbCFuOgF9Trv2MuAyMBUB8kRgk81r1vyq04foQk="

install: mvn dependency:resolve
jobs:
  include:
    - stage: "Build And Test"
      script: mvn clean test
    - stage: "Version Number Upgrade"
      script: bash .scripts/version-number-upgrade.sh
      if: branch = env(DEPLOYMENT_BRANCH) 
          AND type != pull_request
    - stage: "Static Code Analysis"
      script:
        - mvn clean test jacoco:report sonar:sonar -Pcoverage
        - bash <(curl -Ls https://coverage.codacy.com/get.sh)
      if: branch = env(DEPLOYMENT_BRANCH)
    - stage: "Deploy New Release"
      script: 
        - bash .scripts/build-binaries.sh
        - bash .scripts/tag-release.sh
        - TRAVIS_TAG=$APPLICATION_NAME-$APPLICATION_VERSION
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        file_glob: true
        file: $PACKAGEDIR/*
        on:
          tags: true  
          all_branches: true
      if: branch = env(DEPLOYMENT_BRANCH)
          AND type != pull_request