language: java

jdk:
- openjdk13

cache:
  directories:
  - $HOME/.m2

sudo: required
dist: trusty
language: java

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2

sudo: required
dist: trusty

env:
  global:
    - VERSION_MAJOR_NUMBER=0
    - VERSION_MINOR_NUMBER=1
    - VERSION_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - VERSION_BUILD_TYPE="SNAPSHOT"
    - APPLICATION_VERSION="$VERSION_MAJOR_NUMBER.$VERSION_MINOR_NUMBER.$VERSION_BUILD_NUMBER-$VERSION_BUILD_TYPE"


addons:
  sonarcloud:
    organization: "baadamczyk-github"
    token:
      secure: "$SONAR_TOKEN"


jobs:
  include:
    - stage: "build_and_verify"
      name: "Build And Verify"
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -DcheckCodeCoverage sonar:sonar
    - stage: "version_number_upgrade"
      name: "Version Number Upgrade"
      script: bash .scripts/version_number_upgrade.sh
      if: branch = master

env:
  global:
    - VERSION_MAJOR_NUMBER=0
    - VERSION_MINOR_NUMBER=1
    - VERSION_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - VERSION_BUILD_TYPE="SNAPSHOT"
    - APPLICATION_VERSION="$VERSION_MAJOR_NUMBER.$VERSION_MINOR_NUMBER.$VERSION_BUILD_NUMBER-$VERSION_BUILD_TYPE"


addons:
  sonarcloud:
    organization: "baadamczyk-github"
    token:
      secure: "$SONAR_TOKEN"


jobs:
  include:
    - stage: "build_and_verify"
      name: "Build And Verify"
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -DcheckCodeCoverage sonar:sonar
    - stage: "version_number_upgrade"
      name: "Version Number Upgrade"
      script: bash .scripts/version_number_upgrade.sh
      if: branch = master
