language: java

jdk:
- oraclejdk13

cache:
  directories:
  - $HOME/.m2

dist: trusty

env:
  global:
    - APPLICATION_NAME=motosoup
    - VERSION_MAJOR_NUMBER=0
    - VERSION_MINOR_NUMBER=1
    - VERSION_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - APPLICATION_VERSION="$VERSION_MAJOR_NUMBER.$VERSION_MINOR_NUMBER.$VERSION_BUILD_NUMBER"


# addons:
#   sonarcloud:
#     organization: "baadamczyk-github"
#     token:
#       secure: "$SONAR_TOKEN"


jobs:
  include:
    - stage: "build_and_verify"
      name: "Build And Verify"
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
      # script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -DcheckCodeCoverage sonar:sonar
    - stage: "version_number_upgrade"
      name: "Version Number Upgrade"
      script: bash .scripts/version_number_upgrade.sh
      if: branch = master
    - stage: deploy_release
      name: "Deploy new release"
      script: bash .scripts/deploy.sh
      if: branch = master