#!/usr/bin/env bash

# Script variables
PACKAGE_BASE_NAME="$APPLICATION_NAME-$APPLICATION_VERSION"
SOURCEDIR="$WORKDIR/source"
WIN32_RUN_SCRIPT="MotoSoup.bat"
LINUX_RUN_SCRIPT="MotoSoup.sh"
WIN32_ARCHIVE_SUFFIX=windows
LINUX_ARCHIVE_SUFFIX=linux